


    /*
    Nombre	Tipo1 Tipo 2	No. Patas	Color	No. Brazos	Dedos	Colmillos	
    Vuela	Ash	Dinosaurio	Reptil	Roedor	Serpiente	Mamifero	
    Canino	Felino	Pico	Mono	Cola
    */

    const f = false ; 
    const t = true ; 

    const Pokemon1 = {
        posicion: "right -621px bottom -2070px", 
        Nombre: "Bulbasaur",
        Tipo1: "Planta" , 
        Tipo2: "Veneno",
        Patas: 4, 
        Color: "Verde" ,
        Brazos: 0 ,
        Colmillos: true,
        Vuela: false , 
        Ash: true , 
        Dinosaurio: true ,
        Reptil: true , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: true 
        
    }
    const Pokemon2 = {
        posicion: "right -483px bottom -2070px", 
        Nombre: "Ivysaur",
        Tipo1: "Planta" , 
        Tipo2: "Veneno",
        Patas: 4, 
        Color: "Verde" ,
        Brazos: 0 ,
        Colmillos: true,
        Vuela: false , 
        Ash: true , 
        Dinosaurio: true ,
        Reptil: true , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: true 

    }
    const Pokemon3 = {
        posicion: "right -345px bottom -2070px",
        Nombre: "Venasaur",
        Tipo1: "Planta" , 
        Tipo2: "Veneno",
        Patas: 4, 
        Color: "Verde" ,
        Brazos: 0 ,
        Colmillos: true,
        Vuela: false , 
        Ash: true , 
        Dinosaurio: true ,
        Reptil: true , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: true 

    }
    const Pokemon4 = {
        posicion: "right -207px bottom -2070px",
        Nombre: "Charmander",
        Tipo1: "Fuego" , 
        Tipo2: "none",
        Patas: 2, 
        Color: "Rojo" ,
        Brazos: 2 ,
        Colmillos: true,
        Vuela: false , 
        Ash: true , 
        Dinosaurio: true ,
        Reptil: true , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: true 

    }
    const Pokemon5 = {
        posicion: "right -69px bottom -2070px",
        Nombre: "Charmeleon",
        Tipo1: "Fuego" , 
        Tipo2: "none",
        Patas: 2, 
        Color: "Rojo" ,
        Brazos: 2 ,
        Colmillos: true,
        Vuela: false , 
        Ash: true , 
        Dinosaurio: true ,
        Reptil: true , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: true 

    }
    const Pokemon6 = {
        posicion: "right -621px bottom -2001px",
        Nombre: "Charizard",
        Tipo1: "Fuego" , 
        Tipo2: "Volador",
        Patas: 2, 
        Color: "Rojo" ,
        Brazos: 2 ,
        Colmillos: true,
        Vuela: true , 
        Ash: true , 
        Dinosaurio: true ,
        Reptil: true , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: true 

    }
    const Pokemon7 = {
        posicion: "right -483px bottom -2001px",
        Nombre: "Squirtle",
        Tipo1: "Agua" , 
        Tipo2: "none",
        Patas: 2, 
        Color: "Azul" ,
        Brazos: 2 ,
        Colmillos: false,
        Vuela: false , 
        Ash: true , 
        Dinosaurio: false ,
        Reptil: true , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: true 

    }
    const Pokemon8 = {
        posicion: "right -345px bottom -2001px",
        Nombre: "Wartortle",
        Tipo1: "Agua" , 
        Tipo2: "none",
        Patas: 2, 
        Color: "Azul" ,
        Brazos: 2 ,
        Colmillos: false,
        Vuela: false , 
        Ash: true , 
        Dinosaurio: false ,
        Reptil: true , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: true 

    }
    const Pokemon9 = {
        posicion: "right -207px bottom -2001px",
        Nombre: "Blastoise",
        Tipo1: "Agua" , 
        Tipo2: "none",
        Patas: 2, 
        Color: "Azul" ,
        Brazos: 2 ,
        Colmillos: false,
        Vuela: false , 
        Ash: true , 
        Dinosaurio: false ,
        Reptil: true , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: true 

    }
    const Pokemon10 = {
        posicion: "right -69px bottom -2001px",
        Nombre: "Caterpie",
        Tipo1: "Insecto" , 
        Tipo2: "none",
        Patas: 16, 
        Color: "Verde" ,
        Brazos: 0 ,
        Colmillos: false,
        Vuela: false , 
        Ash: true , 
        Dinosaurio: false ,
        Reptil: false , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: true 

    }
    const Pokemon11 = {
        posicion: "right -621px bottom -1932px",
        Nombre: "Metapod",
        Tipo1: "Insecto" , 
        Tipo2: "none",
        Patas: 0, 
        Color: "Verde" ,
        Brazos: 0 ,
        Colmillos: false,
        Vuela: false , 
        Ash: true , 
        Dinosaurio: false ,
        Reptil: false , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: false 

    }
    const Pokemon12 = {
        posicion: "right -483px bottom -1932px",
        Nombre: "Buterfree",
        Tipo1: "Insecto" , 
        Tipo2: "none",
        Patas: 0, 
        Color: "Azul" ,
        Brazos: 0 ,
        Colmillos: false,
        Vuela: false , 
        Ash: true , 
        Dinosaurio: false ,
        Reptil: false , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: false 

    }
    const Pokemon13 = {
        posicion: "right -345px bottom -1932px",
        Nombre: "Weedle",
        Tipo1: "Insecto" , 
        Tipo2: "Veneno",
        Patas: 14, 
        Color: "Amarillo" ,
        Brazos: 0 ,
        Colmillos: false,
        Vuela: false , 
        Ash: false , 
        Dinosaurio: false ,
        Reptil: false , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: true 

    }
    const Pokemon14 = {
        posicion: "right -207px bottom -1932px",
        Nombre: "Kakuna",
        Tipo1: "Insecto" , 
        Tipo2: "Veneno",
        Patas: 0, 
        Color: "Amarillo" ,
        Brazos: 0 ,
        Colmillos: false,
        Vuela: false , 
        Ash: false , 
        Dinosaurio: false ,
        Reptil: false , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: false 

    }
    const Pokemon15 = {
        posicion: "right -69px bottom -1932px",
        Nombre: "Beedrill",
        Tipo1: "Insecto" , 
        Tipo2: "Veneno",
        Patas: 2, 
        Color: "Amarillo" ,
        Brazos: 2 ,
        Colmillos: false,
        Vuela: true , 
        Ash: false , 
        Dinosaurio: false ,
        Reptil: false , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: true 

    }
    const Pokemon16 = {
        posicion: "right -621px bottom -1863px",
        Nombre: "Pidgey",
        Tipo1: "Volador" , 
        Tipo2: "Normal",
        Patas: 2, 
        Color: "Cafe" ,
        Brazos: 0 ,
        Colmillos: false,
        Vuela: true , 
        Ash: true , 
        Dinosaurio: false ,
        Reptil: false , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: true , 
        Cola: true 

    }
    const Pokemon17 = {
        posicion: "right -483px bottom -1863px",
        Nombre: "Pidgeotto",
        Tipo1: "Volador" , 
        Tipo2: "Normal",
        Patas: 2, 
        Color: "Cafe" ,
        Brazos: 0 ,
        Colmillos: false,
        Vuela: true , 
        Ash: true , 
        Dinosaurio: false ,
        Reptil: false , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: true , 
        Cola: true 


    }
    const Pokemon18 = {
        posicion: "right -345px bottom -1863px",
        Nombre: "Pidgeot",
        Tipo1: "Volador" , 
        Tipo2: "Normal",
        Patas: 2, 
        Color: "Cafe" ,
        Brazos: 0 ,
        Colmillos: false,
        Vuela: true , 
        Ash: true , 
        Dinosaurio: false ,
        Reptil: false , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: true , 
        Cola: true 


    }
    const Pokemon19 = {
        posicion: "right -207px bottom -1863px",
        Nombre: "Rattata",
        Tipo1: "Normal" , 
        Tipo2: "none",
        Patas: 4, 
        Color: "Morado" ,
        Brazos: 0 ,
        Colmillos: true,
        Vuela: false , 
        Ash: false , 
        Dinosaurio: false ,
        Reptil: false , 
        Roedor: true ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: true 

    }
    const Pokemon20 = {
        posicion: "right -69px bottom -1863px",
        Nombre: "Raticate",
        Tipo1: "Normal" , 
        Tipo2: "none",
        Patas: 4, 
        Color: "Cafe" ,
        Brazos: 0 ,
        Colmillos: true,
        Vuela: false , 
        Ash: false , 
        Dinosaurio: false ,
        Reptil: false , 
        Roedor: true ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: true 

    }
    const Pokemon21 = {
        posicion: "right -621px bottom -1794px",
        Nombre: "Spearow",
        Tipo1: "Volador" , 
        Tipo2: "Normal",
        Patas: 2, 
        Color: "Cafe" ,
        Brazos: 0 ,
        Colmillos: false,
        Vuela: true , 
        Ash: false , 
        Dinosaurio: false ,
        Reptil: false , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: true , 
        Cola: true 


    }
    const Pokemon22 = {
        posicion: "right -483px bottom -1794px",
        Nombre: "Fearow",
        Tipo1: "Volador" , 
        Tipo2: "Normal",
        Patas: 2, 
        Color: "Cafe" ,
        Brazos: 0 ,
        Colmillos: false,
        Vuela: true , 
        Ash: false , 
        Dinosaurio: false ,
        Reptil: false , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: true , 
        Cola: true 

    }
    const Pokemon23 = {
        posicion: "right -345px bottom -1794px",
        Nombre: "Ekans",
        Tipo1: "Veneno" , 
        Tipo2: "none",
        Patas: 0, 
        Color: "Morado" ,
        Brazos: 0 ,
        Colmillos: true,
        Vuela: false , 
        Ash: false , 
        Dinosaurio: false ,
        Reptil: true , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: true 

    }
    const Pokemon24 = {
        posicion: "right -207px bottom -1794px",
        Nombre: "Arbok",
        Tipo1: "Veneno" , 
        Tipo2: "none",
        Patas: 0, 
        Color: "Morado" ,
        Brazos: 0 ,
        Colmillos: true,
        Vuela: false , 
        Ash: false , 
        Dinosaurio: false ,
        Reptil: true , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: true 

    }
    const Pokemon25 = {
        posicion: "right -69px bottom -1794px",
        Nombre: "Pikachu",
        Tipo1: "Electrico" , 
        Tipo2: "none",
        Patas: 4, 
        Color: "Amarillo" ,
        Brazos: 0 ,
        Colmillos: false,
        Vuela: false , 
        Ash: true , 
        Dinosaurio: false ,
        Reptil: false , 
        Roedor: true ,
        Mamifero: true, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: true 

    }
    const Pokemon26 = {
        posicion: "right -621px bottom -1725px",
        Nombre: "Raichu",
        Tipo1: "Electrico" , 
        Tipo2: "none",
        Patas: 4, 
        Color: "Amarillo" ,
        Brazos: 0 ,
        Colmillos: false,
        Vuela: false , 
        Ash: true , 
        Dinosaurio: false ,
        Reptil: false , 
        Roedor: true ,
        Mamifero: true, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: true 

    }
    const Pokemon27 = {
        posicion: "right -483px bottom -1725px",
        Nombre: "Sandsdrew",
        Tipo1: "Tierra" , 
        Tipo2: "none",
        Patas: 2, 
        Color: "Amarillo" ,
        Brazos: 0 ,
        Colmillos: false,
        Vuela: false , 
        Ash: false , 
        Dinosaurio: true ,
        Reptil: false , 
        Roedor: false ,
        Mamifero: true, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: true 

    }
    const Pokemon28 = {
        posicion: "right -345px bottom -1725px",
        Nombre: "Sandslash",
        Tipo1: "Tierra" , 
        Tipo2: "none",
        Patas: 2, 
        Color: "Amarillo" ,
        Brazos: 0 ,
        Colmillos: false,
        Vuela: false , 
        Ash: false , 
        Dinosaurio: true ,
        Reptil: false , 
        Roedor: false ,
        Mamifero: true, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: true 

    }
    const Pokemon29 = {
        posicion: "right -207px bottom -1725px",
        Nombre: "Niddoran♀",
        Tipo1: "Veneno" , 
        Tipo2: "none",
        Patas: 4, 
        Color: "Azul" ,
        Brazos: 0 ,
        Colmillos: true,
        Vuela: false , 
        Ash: false , 
        Dinosaurio: true ,
        Reptil: false , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: true 

    }
    const Pokemon30 = {
        posicion: "right -69px bottom -1725px",
        Nombre: "Niddorina",
        Tipo1: "Veneno" , 
        Tipo2: "none",
        Patas: 4, 
        Color: "Azul" ,
        Brazos: 0 ,
        Colmillos: true,
        Vuela: false , 
        Ash: false , 
        Dinosaurio: true ,
        Reptil: false , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: true 

    }
    const Pokemon31 = {
        posicion: "right -621px bottom -1656px",
        Nombre: "Nidoqueen",
        Tipo1: "Veneno" , 
        Tipo2: "none",
        Patas: 2, 
        Color: "Azul" ,
        Brazos: 2 ,
        Colmillos: true,
        Vuela: false , 
        Ash: false , 
        Dinosaurio: true ,
        Reptil: false , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: true 

    }
    const Pokemon32 = {
        posicion: "right -483px bottom -1656px",
        Nombre: "Niddoran♂",
        Tipo1: "Veneno" , 
        Tipo2: "none",
        Patas: 4, 
        Color: "Morado" ,
        Brazos: 0 ,
        Colmillos: true,
        Vuela: false , 
        Ash: false , 
        Dinosaurio: true ,
        Reptil: false , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: true 

    }
    const Pokemon33 = {
        posicion: "right -345px bottom -1656px",
        Nombre: "Niddorino",
        Tipo1: "Veneno" , 
        Tipo2: "none",
        Patas: 4, 
        Color: "Morado" ,
        Brazos: 0 ,
        Colmillos: true,
        Vuela: false , 
        Ash: false , 
        Dinosaurio: true ,
        Reptil: false , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: true 

    }
    const Pokemon34 = {
        posicion: "right -207px bottom -1656px",
        Nombre: "Nidoking",
        Tipo1: "Veneno" , 
        Tipo2: "none",
        Patas: 4, 
        Color: "Morado" ,
        Brazos: 0 ,
        Colmillos: true,
        Vuela: false , 
        Ash: false , 
        Dinosaurio: true ,
        Reptil: false , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: true 

    }
    const Pokemon35 = {
        posicion: "right -69px bottom -1656px",
        Nombre: "Clefairy",
        Tipo1: "Hada" , 
        Tipo2: "none",
        Patas: 2, 
        Color: "Rosa" ,
        Brazos: 2 ,
        Colmillos: true,
        Vuela: false , 
        Ash: false , 
        Dinosaurio: false ,
        Reptil: false , 
        Roedor: false ,
        Mamifero: true, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: true 

    }
    const Pokemon36 = {
        posicion: "right -621px bottom -1587px",
        Nombre: "Clefable",
        Tipo1: "Hada" , 
        Tipo2: "none",
        Patas: 2, 
        Color: "Rosa" ,
        Brazos: 2 ,
        Colmillos: true,
        Vuela: false , 
        Ash: false , 
        Dinosaurio: false ,
        Reptil: false , 
        Roedor: false ,
        Mamifero: true, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: true 

    }
    const Pokemon37 = {
        posicion: "right -483px bottom -1587px",
        Nombre: "Vulpix",
        Tipo1: "Fuego" , 
        Tipo2: "none",
        Patas: 4, 
        Color: "Rojo" ,
        Brazos: 0 ,
        Colmillos: false,
        Vuela: false , 
        Ash: false , 
        Dinosaurio: false ,
        Reptil: false , 
        Roedor: false ,
        Mamifero: false, 
        Canino: true, 
        Felino: false ,
        Pico: false , 
        Cola: true 

    }
    const Pokemon38 = {
        posicion: "right -345px bottom -1587px",
        Nombre: "Ninetales",
        Tipo1: "Fuego" , 
        Tipo2: "none",
        Patas: 4, 
        Color: "Rojo" ,
        Brazos: 0 ,
        Colmillos: false,
        Vuela: false , 
        Ash: false , 
        Dinosaurio: false ,
        Reptil: false , 
        Roedor: false ,
        Mamifero: false, 
        Canino: true, 
        Felino: false ,
        Pico: false , 
        Cola: true 

    }
    const Pokemon39 = {
        posicion: "right -207px bottom -1587px",
        Nombre: "Jigglypuff",
        Tipo1: "Normal" , 
        Tipo2: "Hada",
        Patas: 2, 
        Color: "Rosa" ,
        Brazos: 2 ,
        Colmillos: false,
        Vuela: false , 
        Ash: false , 
        Dinosaurio: false ,
        Reptil: false , 
        Roedor: false ,
        Mamifero: true, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: true 

    }
    const Pokemon40 = {
        posicion: "right -69px bottom -1587px",
        Nombre: "Wigglytuff",
        Tipo1: "Normal" , 
        Tipo2: "Hada",
        Patas: 2, 
        Color: "Rosa" ,
        Brazos: 2 ,
        Colmillos: false,
        Vuela: false , 
        Ash: false , 
        Dinosaurio: false ,
        Reptil: false , 
        Roedor: false ,
        Mamifero: true, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: true 


    }
    const Pokemon41 = {
        posicion: "right -621px bottom -1518px",
        Nombre: "Zubat",
        Tipo1: "Veneno" , 
        Tipo2: "Volador",
        Patas: 2, 
        Color: "Azul" ,
        Brazos: 0 ,
        Colmillos: t,
        Vuela: t , 
        Ash: false , 
        Dinosaurio: f ,
        Reptil: f , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: f 

    }
    const Pokemon42 = {
        posicion: "right -483px bottom -1518px",
        Nombre: "Goldbat",
        Tipo1: "Veneno" , 
        Tipo2: "Volador",
        Patas: 2, 
        Color: "Azul" ,
        Brazos: 0 ,
        Colmillos: t,
        Vuela: t , 
        Ash: false , 
        Dinosaurio: f ,
        Reptil: f , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: f 
    }
    const Pokemon43 = {
        posicion: "right -345px bottom -1518px",
        Nombre: "Oddish",
        Tipo1: "Planta" , 
        Tipo2: "Veneno",
        Patas: 2, 
        Color: "Azul" ,
        Brazos: 0 ,
        Colmillos: f,
        Vuela: f , 
        Ash: f , 
        Dinosaurio: f ,
        Reptil: f , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: f 

    }
    const Pokemon44 = {
        posicion: "right -207px bottom -1518px",
        Nombre: "Gloom",
        Tipo1: "Planta" , 
        Tipo2: "Veneno",
        Patas: 2, 
        Color: "Azul" ,
        Brazos: 2 ,
        Colmillos: f,
        Vuela: f , 
        Ash: f , 
        Dinosaurio: f ,
        Reptil: f , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: f 

    }
    const Pokemon45 = {
        posicion: "right -69px bottom -1518px",
        Nombre: "Vileplume",
        Tipo1: "Planta" , 
        Tipo2: "Veneno",
        Patas: 2, 
        Color: "Azul" ,
        Brazos: 2 ,
        Colmillos: f,
        Vuela: f , 
        Ash: f , 
        Dinosaurio: f ,
        Reptil: f , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: f 

    }
    const Pokemon46 = {
        posicion: "right -621px bottom -1449px",
        Nombre: "Paras",
        Tipo1: "Insecto" , 
        Tipo2: "Planta",
        Patas: 4, 
        Color: "Naranja" ,
        Brazos: 0 ,
        Colmillos: true,
        Vuela: false , 
        Ash: f , 
        Dinosaurio: f ,
        Reptil: f , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: f 

    }
    const Pokemon47 = {
        posicion: "right -483px bottom -1449px",
        Nombre: "Parasect",
        Tipo1: "Insecto" , 
        Tipo2: "Planta",
        Patas: 4, 
        Color: "Naranja" ,
        Brazos: 0 ,
        Colmillos: f,
        Vuela: false , 
        Ash: f , 
        Dinosaurio: f ,
        Reptil: f , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: f 

    }
    const Pokemon48 = {
        posicion: "right -345px bottom -1449px",
        Nombre: "Venonat",
        Tipo1: "Insecto" , 
        Tipo2: "Veneno",
        Patas: 2, 
        Color: "Morado" ,
        Brazos: 2 ,
        Colmillos: true,
        Vuela: false , 
        Ash: f , 
        Dinosaurio: f ,
        Reptil: f , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: f 

    }
    const Pokemon49 = {
        posicion: "right -207px bottom -1449px",
        Nombre: "Venomoth",
        Tipo1: "Insecto" , 
        Tipo2: "Veneno",
        Patas: 6, 
        Color: "Morado" ,
        Brazos: 0 ,
        Colmillos: true,
        Vuela: t , 
        Ash: f , 
        Dinosaurio: f ,
        Reptil: f , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: t 

    }
    const Pokemon50 = {
        posicion: "right -69px bottom -1449px",
        Nombre: "Diglett",
        Tipo1: "Tierra" , 
        Tipo2: "none",
        Patas: 0, 
        Color: "Cafe" ,
        Brazos: 0 ,
        Colmillos: f,
        Vuela: false , 
        Ash: f , 
        Dinosaurio: f ,
        Reptil: f , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: f 

    }
    const Pokemon51 = {
        posicion: "right -621px bottom -1380px",
        Nombre: "Dugtrio",
        Tipo1: "Tierra" , 
        Tipo2: "none",
        Patas: 0, 
        Color: "Cafe" ,
        Brazos: 0 ,
        Colmillos: f,
        Vuela: false , 
        Ash: f , 
        Dinosaurio: f ,
        Reptil: f , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: f 

    }
    const Pokemon52 = {
        posicion: "right -483px bottom -1380px",
        Nombre: "Meowth",
        Tipo1: "Normal" , 
        Tipo2: "none",
        Patas: 2, 
        Color: "Amarillo" ,
        Brazos: 2 ,
        Colmillos: true,
        Vuela: false , 
        Ash: f , 
        Dinosaurio: f ,
        Reptil: f , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: t ,
        Pico: false , 
        Cola: true 

    }
    const Pokemon53 = {
        posicion: "right -345px bottom -1380px",
        Nombre: "Persian",
        Tipo1: "Normal" , 
        Tipo2: "none",
        Patas: 4, 
        Color: "Amarillo" ,
        Brazos: 0 ,
        Colmillos: true,
        Vuela: false , 
        Ash: f , 
        Dinosaurio: f ,
        Reptil: f , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: t ,
        Pico: false , 
        Cola: true 

    }
    const Pokemon54 = {
        posicion: "right -207px bottom -1380px",
        Nombre: "Psyduck",
        Tipo1: "Agua" , 
        Tipo2: "none",
        Patas: 2, 
        Color: "Amarillo" ,
        Brazos: 2 ,
        Colmillos: f,
        Vuela: false , 
        Ash: f , 
        Dinosaurio: f ,
        Reptil: f , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: t , 
        Cola: true 

    }
    const Pokemon55 = {
        posicion: "right -69px bottom -1380px",
        Nombre: "Golduck",
        Tipo1: "Agua" , 
        Tipo2: "none",
        Patas: 2, 
        Color: "Amarillo" ,
        Brazos: 2 ,
        Colmillos: f,
        Vuela: false , 
        Ash: f , 
        Dinosaurio: f ,
        Reptil: f , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: t , 
        Cola: true 

    }
    const Pokemon56 = {
        posicion: "right -621px bottom -1311px",
        Nombre: "Mankey",
        Tipo1: "Luchador" , 
        Tipo2: "none",
        Patas: 2, 
        Color: "Cafe" ,
        Brazos: 2 ,
        Colmillos: f,
        Vuela: false , 
        Ash: true , 
        Dinosaurio: f ,
        Reptil: f , 
        Roedor: false ,
        Mamifero: t, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: true 

    }
    const Pokemon57 = {
        posicion: "right -483px bottom -1311px",
        Nombre: "Primeape",
        Tipo1: "Luchador" , 
        Tipo2: "none",
        Patas: 2, 
        Color: "Cafe" ,
        Brazos: 2 ,
        Colmillos: f,
        Vuela: false , 
        Ash: true , 
        Dinosaurio: f ,
        Reptil: f , 
        Roedor: false ,
        Mamifero: t, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: f 

    }
    const Pokemon58 = {
        posicion: "right -345px bottom -1311px",
        Nombre: "Growlithe",
        Tipo1: "Fuego" , 
        Tipo2: "none",
        Patas: 4, 
        Color: "Rojo" ,
        Brazos: 0 ,
        Colmillos: true,
        Vuela: false , 
        Ash: f , 
        Dinosaurio: f ,
        Reptil: f , 
        Roedor: false ,
        Mamifero: false, 
        Canino: t, 
        Felino: false ,
        Pico: false , 
        Cola: true 

    }
    const Pokemon59 = {
        posicion: "right -207px bottom -1311px",
        Nombre: "Arcanine",
        Tipo1: "Fuego" , 
        Tipo2: "none",
        Patas: 4, 
        Color: "Rojo" ,
        Brazos: 0 ,
        Colmillos: true,
        Vuela: false , 
        Ash: f , 
        Dinosaurio: f ,
        Reptil: f , 
        Roedor: false ,
        Mamifero: false, 
        Canino: t, 
        Felino: false ,
        Pico: false , 
        Cola: true 

    }
    const Pokemon60 = {
        posicion: "right -69px bottom -1311px",
        Nombre: "Poliwag",
        Tipo1: "Agua" , 
        Tipo2: "none",
        Patas: 2, 
        Color: "Azul" ,
        Brazos: 0 ,
        Colmillos: f,
        Vuela: false , 
        Ash: f , 
        Dinosaurio: f ,
        Reptil: f , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: true 

    }

    const Pokemon61 = {
        posicion: "right -621px bottom -1242px",
        Nombre: "Poliwhirl",
         Tipo1: "Agua" , 
        Tipo2: "none",
        Patas: 2, 
        Color: "Azul" ,
        Brazos: 2 ,
        Colmillos: f,
        Vuela: false , 
        Ash: f , 
        Dinosaurio: f ,
        Reptil: f , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: f 

    }
    const Pokemon62 = {
        posicion: "right -483px bottom -1242px",
        Nombre: "Poliwrath",
        Tipo1: "Agua" , 
        Tipo2: "Luchador",
        Patas: 2, 
        Color: "Azul" ,
        Brazos: 2 ,
        Colmillos: f,
        Vuela: false , 
        Ash: f , 
        Dinosaurio: f ,
        Reptil: f , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: f 

    }
    const Pokemon63 = {
        posicion: "right -345px bottom -1242px",
        Nombre: "Abra",
        Tipo1: "Psiquico" , 
        Tipo2: "none",
        Patas: 2, 
        Color: "Amarillo" ,
        Brazos: 2 ,
        Colmillos: f,
        Vuela: false , 
        Ash: f , 
        Dinosaurio: f ,
        Reptil: f , 
        Roedor: false ,
        Mamifero: t, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: true 

    }
    const Pokemon64 = {
        posicion: "right -207px bottom -1242px",
        Nombre: "Kadabra",
        Tipo1: "Psiquico" , 
        Tipo2: "none",
        Patas: 2, 
        Color: "Amarillo" ,
        Brazos: 2 ,
        Colmillos: f,
        Vuela: false , 
        Ash: f , 
        Dinosaurio: f ,
        Reptil: f , 
        Roedor: false ,
        Mamifero: t, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: true 

    }
    const Pokemon65 = {
        posicion: "right -69px bottom -1242px",
        Nombre: "Alakazam",
        Tipo1: "Psiquico" , 
        Tipo2: "none",
        Patas: 2, 
        Color: "Amarillo" ,
        Brazos: 2 ,
        Colmillos: f,
        Vuela: false , 
        Ash: f , 
        Dinosaurio: f ,
        Reptil: f , 
        Roedor: false ,
        Mamifero: t, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: f 

    }
    const Pokemon66 = {
        posicion: "right -621px bottom -1173px",
        Nombre: "Machop",
        Tipo1: "Luchador" , 
        Tipo2: "none",
        Patas: 2, 
        Color: "Gris" ,
        Brazos: 2 ,
        Colmillos: f,
        Vuela: false , 
        Ash: f , 
        Dinosaurio: f ,
        Reptil: f , 
        Roedor: false ,
        Mamifero: t, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: true 

    }
    const Pokemon67 = {
        posicion: "right -483px bottom -1173px",
        Nombre: "Machoke",
        Tipo1: "Luchador" , 
        Tipo2: "none",
        Patas: 2, 
        Color: "Azul" ,
        Brazos: 2 ,
        Colmillos: t,
        Vuela: false , 
        Ash: f , 
        Dinosaurio: f ,
        Reptil: f , 
        Roedor: false ,
        Mamifero: t, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: f 

    }
    const Pokemon68 = {
        posicion: "right -345px bottom -1173px",
        Nombre: "Machamp",
        Tipo1: "Luchador" , 
        Tipo2: "none",
        Patas: 2, 
        Color: "Gris" ,
        Brazos: 4 ,
        Colmillos: f,
        Vuela: false , 
        Ash: f , 
        Dinosaurio: f ,
        Reptil: f , 
        Roedor: false ,
        Mamifero: t, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: f 

    }
    const Pokemon69 = {
        posicion: "right -207px bottom -1173px",
        Nombre: "Bellsprout",
        Tipo1: "Planta" , 
        Tipo2: "Veneno",
        Patas: 2, 
        Color: "Amarillo" ,
        Brazos: 2 ,
        Colmillos: f,
        Vuela: false , 
        Ash: f , 
        Dinosaurio: f ,
        Reptil: f , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: f , 
        Cola: f 

    }
    const Pokemon70 = {
        posicion: "right -69px bottom -1173px",
        Nombre: "Weepinbell",
        Tipo1: "Planta" , 
        Tipo2: "Veneno",
        Patas: 0, 
        Color: "Amarillo" ,
        Brazos: 2 ,
        Colmillos: f,
        Vuela: false , 
        Ash: f , 
        Dinosaurio: f ,
        Reptil: f , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: f , 
        Cola: f 

    }
    const Pokemon71 = {
        posicion: "right -621px bottom -1104px",
        Nombre: "Victreebell",
        Tipo1: "Planta" , 
        Tipo2: "Veneno",
        Patas: 0, 
        Color: "Amarillo" ,
        Brazos: 2 ,
        Colmillos: t,
        Vuela: false , 
        Ash: f , 
        Dinosaurio: f ,
        Reptil: f , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: f , 
        Cola: f 

    }
    const Pokemon72 = {
        posicion: "right -483px bottom -1104px",
        Nombre: "Tentacool",
        Tipo1: "Agua" , 
        Tipo2: "Veneno",
        Patas: 0, 
        Color: "Azul" ,
        Brazos: 2 ,
        Colmillos: f,
        Vuela: false , 
        Ash: f , 
        Dinosaurio: f ,
        Reptil: f , 
        Roedor: false ,
        Mamifero: false, 
        Canino: false, 
        Felino: false ,
        Pico: false , 
        Cola: f 

    }
   
    const Pokemones = [ 
        Pokemon1,
        Pokemon2,
        Pokemon3,
        Pokemon4,
        Pokemon5,
        Pokemon6, 
        Pokemon7,
        Pokemon8,
        Pokemon9,
        Pokemon10,
        Pokemon11,
        Pokemon12,
        Pokemon13,
        Pokemon14,
        Pokemon15,
        Pokemon16, 
        Pokemon17,
        Pokemon18,
        Pokemon19,
        Pokemon20,
        Pokemon21,
        Pokemon22,
        Pokemon23,
        Pokemon24,
        Pokemon25,
        Pokemon26, 
        Pokemon27,
        Pokemon28,
        Pokemon29,
        Pokemon30,
        Pokemon31,
        Pokemon32,
        Pokemon33,
        Pokemon34,
        Pokemon35,
        Pokemon36, 
        Pokemon37,
        Pokemon38,
        Pokemon39,
        Pokemon40,
        Pokemon41,
        Pokemon42,
        Pokemon43,
        Pokemon44,
        Pokemon45,
        Pokemon46, 
        Pokemon47,
        Pokemon48,
        Pokemon49,
        Pokemon50,
        Pokemon51,
        Pokemon52,
        Pokemon53,
        Pokemon54,
        Pokemon55,
        Pokemon56, 
        Pokemon57,
        Pokemon58,
        Pokemon59,
        Pokemon60,
        Pokemon61,
        Pokemon62,
        Pokemon63,
        Pokemon64,
        Pokemon65,
        Pokemon66, 
        Pokemon67,
        Pokemon68,
        Pokemon69,
        Pokemon70,
        Pokemon71,
        Pokemon72,
    
    ] ;
export default Pokemones ; 
